name: Build lyes.eu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: fedora-latest
    steps:
      - name: install dependencies
        run: |
          dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
          dnf install -y typst nodejs24 git
          mv /usr/bin/node-24 /usr/bin/node
      - name: checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: build
        run: |
          for f in *.typ; do
            typst c $f --input scheme=dark
          done
          mkdir output
          mv *.pdf output
      - name: upload part 1
        uses: forgejo/upload-artifact@v4
        with:
          name: SEMPL.zip
          path: output
          if-no-files-found: error
